//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Key]
        public int id { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "用户帐号")]
        public string Account { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name="用户名")]
        public string Name { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "用户密码")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
